### ISSUE TITLE
Sometimes not working

### ISSUE THREAD

**Issue by josete89** [BarryReid/another-diawi-cli#1]
Not working always:
found token : qQGv8Ok9LM33UiUsZrhWtQMcAS8CMzaEbsJugerDez
Uploading File...
Upload complete!
Posting File...
xHMgBiaBi9BimC9p60fZ3oAIx19QIw03dN84KksfbO
Getting status...
Your app failed to post

**Comment by BarryReid** [comment]
I cant seem to replicate the problem. I have updated the master branch with some debugging. Can you please try recreate the problem with --debug set and then post the output.

**Comment by josete89** [comment]
debug : found file /Users/alcaljos/.jenkins/jobs/Build/AdidasEndlessAisle.ipa
debug : valid file extention : .ipa
debug : temp file name : o_uzmolc25983iax0qq65gi79zrr0z5.ipa
log : found token : qQGv8Ok9LM33UiUsZrhWtQMcAS8CMzaEbsJugerDez
log : Uploading File...
debug : file upload responce code : 200
debug : file upload responce text : {"OK":1}
log : Upload complete!
log : Posting File...
debug : file post responce code : 200
debug : file post responce text : {"job":"wDvXDWF7OXHuPyANzQVEOtEQQwjrEZfql8kW3V8pOK"}
log : wDvXDWF7OXHuPyANzQVEOtEQQwjrEZfql8kW3V8pOK
log : Getting status...
debug : job status responce code : 200
debug : job status responce text : {"status":2001,"message":"Processing, please try again in a few seconds..."}
log : Your app failed to post

**Comment by BarryReid** [comment]
Ah, I see the problem.

**Comment by BarryReid** [comment]
OK, I have updated the code to retry if it gets code 2001. I have not tested it so please let me know if it works.

**Comment by josete89** [comment]
Works like a charm! Thanks!
